# Introduction to tensorflow


In [1]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [2]:
# importing tensorflow

import tensorflow as tf

print(tf.__version__)

2.12.0


In [3]:
#creating tensors with tf.constants()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# checking the number of dimensions of aa tensor (ndim stands form number of dimensions)

scalar.ndim

0

In [5]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
# check the dimesnion of our vector

vector.ndim

1

In [7]:
matrix = tf.constant([[10,20],[20,30]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [20, 30]])>

In [8]:
matrix.ndim

2

In [9]:
# create another matrix

another_matrix = tf.constant([[10,20],[20,30],[50,30]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10., 20.],
       [20., 30.],
       [50., 30.]], dtype=float16)>

In [10]:
another_matrix.ndim


2

In [11]:
# creating tensor

tensor = tf.constant([[[1,2,3],[4,5,6]],
                     [[10,100,20],[2,4,6]],
                      [[12,4,5],[5,34,70]]
                     ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[ 10, 100,  20],
        [  2,   4,   6]],

       [[ 12,   4,   5],
        [  5,  34,  70]]])>

In [12]:
tensor.ndim


3

# what we have created

* Scalar: a single number
* Vector : a number with direction
* Matrix :  2-d dimensional array of number
* Tensor : an n-dimensional array of numbers(when n can be number , a 0-dimensional tensor is a scalar,a 1-dimensional tensor is a vector)
    

## Creating tensors with variables 

In [13]:
# create the same tensor with tf.variable()

changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])

changable_tensor,unchangable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [14]:
changable_tensor[0].assign(7)
changable_tensor
 

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

# Creating random tensors

Random tensors  are tensors of some arbituary numbers

In [15]:
# creating random tensors

random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1,random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [16]:
# shuffle a tensor 

not_shuffled = tf.constant([[10,7],[20,20],[20,23]])

#shuffle non shuffle data
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 23],
       [10,  7],
       [20, 20]])>

In [17]:
# Practicing 5 random tf seeds

value_1 = tf.Variable([[1,2,3],[2,3,4],[2,34,33]])

tf.random.set_seed(12)
tf.random.shuffle(value_1,seed=10)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  3,  4],
       [ 1,  2,  3],
       [ 2, 34, 33]])>

In [18]:
value_2 = tf.constant([[[1,2,3],[2,3,5]],
                      [[1,2,34],[3,5,6]],
                       [[2,3,5],[2,3,5]]
                      ])

# tf.random.set_seed(100)
tf.random.shuffle(value_2,seed=11)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2, 34],
        [ 3,  5,  6]],

       [[ 2,  3,  5],
        [ 2,  3,  5]],

       [[ 1,  2,  3],
        [ 2,  3,  5]]])>

# Crash course on numpy

In [19]:
import numpy as np 

In [20]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [21]:
a.shape


(3,)

In [22]:
a.dtype

dtype('int32')

In [23]:
a.itemsize

4

# other ways to make tensors


In [24]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [25]:
# creating tensor of all zeros

tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## Turning numpy array into tensors
The main difference between numpy array and tensors is that tensors can be run on GPU


In [26]:
# TUrning into tensors

import numpy as np

numpy_A = np.arange(1,25,dtype=np.int32)

numpy_A
# X = tf.constant(s)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [27]:
A = tf.constant(numpy_A,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [28]:
A.ndim

3

In [29]:
tf.random.shuffle(A,seed=10)
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

# Getting information from tensors

When dealing with tensors you probably want to be aware of the following 

* Shape
* Rank 
* Axis or Dimension
* Sizw

In [30]:
# Create a rank 4 tensors 

rank_4_tensors = tf.zeros(shape=[2,3,4,5])

rank_4_tensors

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
rank_4_tensors[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [32]:
rank_4_tensors.shape, rank_4_tensors.ndim,tf.size(rank_4_tensors)


(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [33]:
#  Get various attributes of our tensor

print("Data type of every elements:", rank_4_tensors.dtype)
print("Number of dimensions (rank):", rank_4_tensors.ndim)
print("SHape of tensor", rank_4_tensors.shape)
print("Elements along the 0 axis: ", rank_4_tensors.shape[0])
print("Elements along the last axis:", rank_4_tensors.shape[-1])


Data type of every elements: <dtype: 'float32'>
Number of dimensions (rank): 4
SHape of tensor (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis: 5


# Indexing tensors

Tensors can be indexed like python lists

In [34]:
# Get the first 2 element of each dimensions

rank_4_tensors[:2,:3,:4,:5]

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [35]:
#  Get the first element from each dimension from each index expcept for the final one

rank_4_tensors[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [36]:
rank_2_tensor = tf.constant([[10,7],[2,2]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  2]])>

In [37]:
# get the last item of each of row of our rank 2 tensor

rank_2_tensor[:-1]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[10,  7]])>

In [38]:
#  Adding in extra dimension to our rank 2 tensor

rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 2]]])>

In [39]:
#  Alternative to tf.newaxis

tf.expand_dims(rank_2_tensor,axis=1)


<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 2,  2]]])>

### Manipulating tensors (tensors operations)

**Basic Operations**

'+','-',*,/

In [40]:
tensor = tf.constant([[10,5],[10,4]])
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 15],
       [20, 14]])>

In [41]:
# Multiplication 

tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  50],
       [100,  40]])>

## Matrix multiplication

In [42]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[150,  70],
       [140,  66]])>

In [43]:
# creTE A TENSOR (3,2)

x = tf.constant([[1,2],[3,5],[5,7]])

y = tf.constant([[1,2,5],[3,4,5]])

tf.matmul(x,y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 7, 10, 15],
       [18, 26, 40],
       [26, 38, 60]])>

**The Dot Product**

Matrix multiplication is also referred to as the dot product

You can perform matri multiplication using:

* `tf.matmul()`
*  `tf.tesnordot()`


In [44]:
#  Perform the dot product on X and Y 

tf.tensordot(tf.transpose(x),tf.reshape(y,shape=[3,2]),axes=1)
# x,y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[36, 36],
       [55, 54]])>

In [45]:
# Create a new tensor with default datatype

B = tf.constant([1.4,2.3,3.4])
B

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.4, 2.3, 3.4], dtype=float32)>

In [46]:
B = tf.cast(B,dtype=tf.int32)
B

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

# Aggregrating tensors

Aggregrating tensors = condensing them from multiple values down to a smaller amount


In [47]:
#  Get the absolute valuee

D = tf.constant([-1,201,10],dtype=tf.int32)
D

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ -1, 201,  10])>

In [48]:
tf.abs(D)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  1, 201,  10])>

**Going through  the following forms of aggregration**
* Get the maximum
* Get the minimum
* Get the mean of tensor
* Get the sum of a tensor

In [49]:
tf.maximum(D,B)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  1, 201,  10])>

In [50]:
tf.minimum(D,B)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-1,  2,  3])>

In [51]:
tf.reduce_mean(D)

<tf.Tensor: shape=(), dtype=int32, numpy=70>

In [52]:
E = tf.constant(np.random.randint(0,100,size=50))

In [53]:
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([87, 60, 87, 62,  3, 39, 87, 94, 22, 16, 84, 86, 90, 74, 99, 36, 26,
        5, 88, 55, 64, 31, 19,  0, 27, 14, 51, 10, 58, 79, 30, 41, 82, 63,
       92, 15, 16, 45, 95, 44, 97, 11, 10, 63, 43, 77, 57, 91, 68, 17])>

In [54]:
tf.size(E),tf.shape(E), E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([50])>,
 1)

In [55]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [56]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [57]:
mean = tf.reduce_mean(E)

In [58]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2610>

In [59]:
# finding variance and standard deviation using tensorflow methods

sub_mean = [x - mean for x in E ]
sub_mean

[<tf.Tensor: shape=(), dtype=int32, numpy=35>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>,
 <tf.Tensor: shape=(), dtype=int32, numpy=35>,
 <tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-49>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-13>,
 <tf.Tensor: shape=(), dtype=int32, numpy=35>,
 <tf.Tensor: shape=(), dtype=int32, numpy=42>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-30>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-36>,
 <tf.Tensor: shape=(), dtype=int32, numpy=32>,
 <tf.Tensor: shape=(), dtype=int32, numpy=34>,
 <tf.Tensor: shape=(), dtype=int32, numpy=38>,
 <tf.Tensor: shape=(), dtype=int32, numpy=22>,
 <tf.Tensor: shape=(), dtype=int32, numpy=47>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-16>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-26>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-47>,
 <tf.Tensor: shape=(), dtype=int32, numpy=36>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=12>,
 <tf.Ten

In [60]:
square_sub_mean = np.square(sub_mean)
square_sub_mean

array([1225,   64, 1225,  100, 2401,  169, 1225, 1764,  900, 1296, 1024,
       1156, 1444,  484, 2209,  256,  676, 2209, 1296,    9,  144,  441,
       1089, 2704,  625, 1444,    1, 1764,   36,  729,  484,  121,  900,
        121, 1600, 1369, 1296,   49, 1849,   64, 2025, 1681, 1764,  121,
         81,  625,   25, 1521,  256, 1225])

In [61]:
total_value = sum(square_sub_mean)

In [62]:
total_value

47286

In [63]:
variance = total_value/ (len(E)-1)
variance

965.0204081632653

In [64]:
std_dev = tf.sqrt(variance)
std_dev

<tf.Tensor: shape=(), dtype=float64, numpy=31.06477761329164>

In [65]:
pip install tensorflow_probability

Note: you may need to restart the kernel to use updated packages.


In [66]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.751911>

In [67]:
# Create a new tensor for finding positional minimum and maximum

tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [68]:
# Fi d the positional maximum

tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [69]:
# index of largest value
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [70]:
assert F[tf.argmax(F)] == tf.reduce_max(F)

## Sqeezing tensors
creating tensors or romoving 1-d array

In [72]:
tf.random.set_seed(43)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.2733041 , 0.5020257 , 0.6628481 , 0.6473899 , 0.3857293 ,
           0.36172044, 0.5412978 , 0.48597205, 0.8773687 , 0.19192028,
           0.9264002 , 0.89626896, 0.6672703 , 0.47216296, 0.22052324,
           0.88224113, 0.21332026, 0.3742751 , 0.6198429 , 0.67401516,
           0.33629417, 0.04864144, 0.00223255, 0.9375315 , 0.1595205 ,
           0.76488817, 0.5631764 , 0.48775423, 0.4250028 , 0.29910493,
           0.8409952 , 0.6727512 , 0.00153816, 0.4085456 , 0.9261861 ,
           0.18742752, 0.60272205, 0.99417937, 0.42423892, 0.27978897,
           0.9430332 , 0.80545497, 0.06359637, 0.56783044, 0.26592016,
           0.98973536, 0.5452112 , 0.11514163, 0.53635466, 0.6935723 ]]]]],
      dtype=float32)>

In [74]:
G.shape


TensorShape([1, 1, 1, 1, 50])

In [75]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.2733041 , 0.5020257 , 0.6628481 , 0.6473899 , 0.3857293 ,
        0.36172044, 0.5412978 , 0.48597205, 0.8773687 , 0.19192028,
        0.9264002 , 0.89626896, 0.6672703 , 0.47216296, 0.22052324,
        0.88224113, 0.21332026, 0.3742751 , 0.6198429 , 0.67401516,
        0.33629417, 0.04864144, 0.00223255, 0.9375315 , 0.1595205 ,
        0.76488817, 0.5631764 , 0.48775423, 0.4250028 , 0.29910493,
        0.8409952 , 0.6727512 , 0.00153816, 0.4085456 , 0.9261861 ,
        0.18742752, 0.60272205, 0.99417937, 0.42423892, 0.27978897,
        0.9430332 , 0.80545497, 0.06359637, 0.56783044, 0.26592016,
        0.98973536, 0.5452112 , 0.11514163, 0.53635466, 0.6935723 ],
       dtype=float32)>,
 TensorShape([50]))

## One hot encode

It is one way of encoding the data into numbers


In [90]:
# Create the number of list of indices

some_list = [1,2,3,4]
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [91]:
tf.one_hot(some_list,depth=4,on_value="Yo I love dancing",off_value="I dont love dancing")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I dont love dancing', b'Yo I love dancing',
        b'I dont love dancing', b'I dont love dancing'],
       [b'I dont love dancing', b'I dont love dancing',
        b'Yo I love dancing', b'I dont love dancing'],
       [b'I dont love dancing', b'I dont love dancing',
        b'I dont love dancing', b'Yo I love dancing'],
       [b'I dont love dancing', b'I dont love dancing',
        b'I dont love dancing', b'I dont love dancing']], dtype=object)>

In [94]:
tf.one_hot(some_list,depth=2,on_value=3)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 3],
       [0, 0],
       [0, 0],
       [0, 0]])>

## Squaring,log,squareroot

In [96]:
h = tf.range(1,10)
h

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [97]:
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [98]:
tf.sqrt(tf.cast(h,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [101]:
tf.math.log(tf.cast(h,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [106]:
i = 10
tf.add(h,i)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([11, 12, 13, 14, 15, 16, 17, 18, 19])>

## Tensorflow and numpy

In [108]:
#Create a tensor directly from a Numpy array

J = tf.constant(np.array([2.,3,4,5]))
J

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([2., 3., 4., 5.])>

In [110]:
np.array(J)

array([2., 3., 4., 5.])

## Finding access to gpu

In [113]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]